// guide/packages/angular/src/components/chat-panel.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  EventEmitter,
  Input,
  OnInit,
  Output,
  TemplateRef,
  computed,
  inject,
  signal,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import type { ChatMessage, ComponentCitation } from "@freebirdai/core";
import {
  activateCitation,
  citationsFromToolPayload,
  replayPendingCitation,
} from "@freebirdai/core";
import { FreeBirdService } from "../services/freebird.service";

/**
 * Host hook for client-side routing when a citation targets another page.
 * Return `false` to fall back to a full-page `location.assign`; anything
 * else (including void) means the host's router handled it.
 */
export type CitationNavigateHandler = (
  path: string,
  citation: ComponentCitation,
) => void | boolean | Promise<void | boolean>;

/**
 * Root wrapper for the chat panel. Auto-creates a session on init unless
 * `[sessionAutoCreate]="false"` is supplied. Matches the React
 * `<ChatPanel.Root>` API.
 */
@Component({
  selector: "fb-chat-panel",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div data-freebird-chat><ng-content /></div>`,
})
export class ChatPanelComponent implements OnInit {
  private readonly fb = inject(FreeBirdService);

  @Input() sessionAutoCreate = true;
  @Input() sessionTopic?: string;
  @Input() sessionTags?: string[];

  async ngOnInit(): Promise<void> {
    // A citation click may have navigated here — finish the scroll+highlight.
    void replayPendingCitation();
    if (!this.sessionAutoCreate) return;
    if (this.fb.sessionId()) return;
    try {
      await this.fb.createSession({
        topic: this.sessionTopic,
        tags: this.sessionTags,
      });
    } catch (err) {
       
      console.error("[freebird] auto createSession failed:", err);
    }
  }
}

/**
 * Scoped-slot-style messages renderer. Provide a `<ng-template>` with
 * `let-messages="messages"` / `let-streamingText="streamingText"`.
 */
@Component({
  selector: "fb-chat-panel-messages",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div data-freebird-chat-messages>
      <ng-container
        *ngIf="tpl"
        [ngTemplateOutlet]="tpl"
        [ngTemplateOutletContext]="context()"
      />
    </div>
  `,
})
export class ChatPanelMessagesComponent {
  private readonly fb = inject(FreeBirdService);
  @ContentChild(TemplateRef) tpl?: TemplateRef<{
    $implicit: ChatMessage[];
    messages: ChatMessage[];
    streamingText: string;
    streaming: boolean;
  }>;

  readonly context = computed(() => ({
    $implicit: this.fb.messages(),
    messages: this.fb.messages(),
    streamingText: this.fb.streamingText(),
    streaming: this.fb.streaming(),
  }));
}

/**
 * Form wrapper that binds an input (via the `[fbChatPanelInput]` directive)
 * and a submit button, and wires them to `FreeBirdService.send()`.
 *
 * Because Angular doesn't have React context, we use template reference
 * variables + exportAs instead of provide/inject here — easier to read in
 * templates:
 *
 *   <fb-chat-panel-form #form>
 *     <input fbChatPanelInput [form]="form" />
 *     <button fbChatPanelSubmit [form]="form">Send</button>
 *   </fb-chat-panel-form>
 */
@Component({
  selector: "fb-chat-panel-form",
  standalone: true,
  exportAs: "fbChatPanelForm",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <form data-freebird-chat-form (submit)="onSubmit($event)">
      <ng-content />
    </form>
  `,
})
export class ChatPanelFormComponent {
  private readonly fb = inject(FreeBirdService);

  @Input() beforeSend?: (text: string) => boolean | Promise<boolean>;
  @Output() afterSend = new EventEmitter<void>();

  readonly value = signal<string>("");
  readonly streaming = this.fb.streaming;
  readonly sessionReady = computed(() => this.fb.sessionId() != null);

  setValue(v: string): void {
    this.value.set(v);
  }

  async submit(): Promise<void> {
    const text = this.value().trim();
    if (!text || this.streaming() || !this.sessionReady()) return;
    if (this.beforeSend && (await this.beforeSend(text)) === false) return;
    this.value.set("");
    try {
      await this.fb.send(text);
    } finally {
      this.afterSend.emit();
    }
  }

  onSubmit(e: Event): void {
    e.preventDefault();
    void this.submit();
  }
}

/**
 * Directive-style input that binds to a parent form by template ref.
 * Implemented as a component for simpler template syntax.
 */
@Component({
  selector: "input[fbChatPanelInput]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: ``,
  host: {
    "data-freebird-chat-input": "",
    type: "text",
    "[value]": "form?.value() ?? ''",
    "[disabled]":
      "!!form && (form.streaming() || !form.sessionReady() || disabled)",
    "(input)": "onInput($event)",
  },
})
export class ChatPanelInputComponent {
  @Input() form?: ChatPanelFormComponent;
  @Input() disabled = false;

  onInput(e: Event): void {
    const v = (e.target as HTMLInputElement).value;
    this.form?.setValue(v);
  }
}

/**
 * Submit button bound to a parent form by template ref.
 */
@Component({
  selector: "button[fbChatPanelSubmit]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<ng-content />`,
  host: {
    type: "submit",
    "data-freebird-chat-submit": "",
    "[attr.data-streaming]": "form?.streaming() ? '' : null",
    "[disabled]":
      "!form || form.streaming() || !form.sessionReady() || !form.value().trim() || disabled",
  },
})
export class ChatPanelSubmitComponent {
  @Input() form?: ChatPanelFormComponent;
  @Input() disabled = false;
}

/**
 * Citation chips under an assistant reply — matches React's
 * `<ChatPanel.Citations>`. Also usable standalone.
 */
@Component({
  selector: "fb-chat-panel-citations",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div *ngIf="citations.length" data-freebird-chat-citations>
      <button
        *ngFor="let c of citations; let i = index"
        type="button"
        data-freebird-chat-citation
        [attr.data-kind]="c.kind ?? 'component'"
        [attr.data-component]="c.componentId"
        (click)="onChipClick(c)"
      >
        {{ c.title }}
      </button>
    </div>
  `,
})
export class ChatPanelCitationsComponent {
  @Input({ required: true }) message!: ChatMessage;
  /** Client-side routing hook for cross-page citations. */
  @Input() onCitationNavigate?: CitationNavigateHandler;

  get citations(): ComponentCitation[] {
    if (this.message.role !== "assistant") return [];
    return citationsFromToolPayload(this.message.toolPayload);
  }

  onChipClick(citation: ComponentCitation): void {
    void activateCitation(citation, {
      ...(this.onCitationNavigate ? { onNavigate: this.onCitationNavigate } : {}),
    });
  }
}

/**
 * Convenience single-message renderer — matches React's
 * `<ChatPanel.Message>`.
 */
@Component({
  selector: "fb-chat-panel-message",
  standalone: true,
  imports: [CommonModule, ChatPanelCitationsComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      data-freebird-chat-message
      [attr.data-role]="message.role"
    >
      {{ message.content }}
      <div *ngIf="message.references?.length" data-freebird-chat-refs>
        <span
          *ngFor="let r of message.references; let i = index"
          data-freebird-chat-ref
          [attr.data-tag]="r.tag"
          [attr.data-component]="r.componentId"
        >
          {{ r.reason }}
        </span>
      </div>
      <fb-chat-panel-citations
        [message]="message"
        [onCitationNavigate]="onCitationNavigate"
      />
    </div>
  `,
})
export class ChatPanelMessageComponent {
  @Input({ required: true }) message!: ChatMessage;
  /** Client-side routing hook for cross-page citation chips. */
  @Input() onCitationNavigate?: CitationNavigateHandler;
}

// packages/react/src/components/ChatPanel.tsx
import React, { useEffect, useState } from "react";
import type { ChatMessage, ComponentCitation } from "@freebirdai/core";
import {
  activateCitation,
  citationsFromToolPayload,
  replayPendingCitation,
} from "@freebirdai/core";
import { useChat } from "../hooks/useChat.js";
import { useSession } from "../hooks/useSession.js";
import { useFreeBird } from "../provider.js";
import { slotWith, type SlotProps } from "./Slot.js";

/**
 * Host hook for client-side routing when a citation targets another page.
 * Return `false` to fall back to a full-page `location.assign`; anything
 * else (including void) means the host's router handled it.
 */
export type CitationNavigateHandler = (
  path: string,
  citation: ComponentCitation,
) => void | boolean | Promise<void | boolean>;

/**
 * Headless ChatPanel primitives. Compose them yourself:
 *
 * <ChatPanel.Root>
 *   <ChatPanel.Messages>
 *     {({ messages, streamingText }) => messages.map(...)}
 *   </ChatPanel.Messages>
 *   <ChatPanel.Form>
 *     <ChatPanel.Input />
 *     <ChatPanel.Submit>Send</ChatPanel.Submit>
 *   </ChatPanel.Form>
 * </ChatPanel.Root>
 *
 * Every primitive stamps `data-freebird-*` attributes so any styling system
 * can hook onto them. @freebirdai/react-tailwind ships a pre-styled variant.
 */

// ---------------------------------------------------------------------------
// Root (just a scoped wrapper + data attrs)
// ---------------------------------------------------------------------------
export interface ChatPanelRootProps
  extends React.HTMLAttributes<HTMLDivElement>,
    SlotProps {
  /**
   * When true (default), creates a chat session on mount so `useChat().send`
   * works immediately. Set false if you manage sessions yourself with
   * `useSession({ autoCreate: false })`.
   */
  sessionAutoCreate?: boolean;
  /** Passed to the auto-created session (optional). */
  sessionTopic?: string;
  /** Passed to the auto-created session (optional). */
  sessionTags?: string[];
}

const Root: React.FC<ChatPanelRootProps> = (props) => {
  const {
    sessionAutoCreate = true,
    sessionTopic,
    sessionTags,
    ...rest
  } = props;
  useSession({
    autoCreate: sessionAutoCreate,
    topic: sessionTopic,
    tags: sessionTags,
  });
  // A citation click may have navigated here — finish the scroll+highlight.
  useEffect(() => {
    void replayPendingCitation();
  }, []);
  return slotWith("div", { ...rest, "data-freebird-chat": "" } as any);
};

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------
export interface ChatPanelMessagesRenderProps {
  messages: ChatMessage[];
  streamingText: string;
  streaming: boolean;
}

export interface ChatPanelMessagesProps {
  /** Render prop — do anything you want with the message list. */
  children: (state: ChatPanelMessagesRenderProps) => React.ReactNode;
  className?: string;
}

const Messages: React.FC<ChatPanelMessagesProps> = ({ children, className }) => {
  const chat = useChat();
  return (
    <div data-freebird-chat-messages="" className={className}>
      {children({
        messages: chat.messages,
        streamingText: chat.streamingText,
        streaming: chat.streaming,
      })}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Form (wraps an <input> and a submit button, wires to useChat.send)
// ---------------------------------------------------------------------------
export interface ChatPanelFormProps
  extends Omit<React.FormHTMLAttributes<HTMLFormElement>, "onSubmit"> {
  /** Called before send with the raw text. Return false to cancel. */
  beforeSend?: (text: string) => boolean | Promise<boolean>;
  /** Called after send finishes (success or error). */
  afterSend?: () => void;
  children: React.ReactNode;
}

interface FormCtxValue {
  value: string;
  setValue: (v: string) => void;
  streaming: boolean;
  /** False while the default auto-created session is still being created. */
  sessionReady: boolean;
  submit: () => void;
}
const FormCtx = React.createContext<FormCtxValue | null>(null);

const Form: React.FC<ChatPanelFormProps> = ({ beforeSend, afterSend, children, ...rest }) => {
  const { send, streaming } = useChat();
  const fb = useFreeBird();
  const [value, setValue] = useState("");

  const submit = async () => {
    const text = value.trim();
    if (!text || streaming || !fb.sessionId) return;
    if (beforeSend && (await beforeSend(text)) === false) return;
    setValue("");
    try {
      await send(text);
    } finally {
      afterSend?.();
    }
  };

  return (
    <FormCtx.Provider
      value={{
        value,
        setValue,
        streaming,
        sessionReady: fb.sessionId != null,
        submit,
      }}
    >
      <form
        data-freebird-chat-form=""
        {...rest}
        onSubmit={(e) => {
          e.preventDefault();
          void submit();
        }}
      >
        {children}
      </form>
    </FormCtx.Provider>
  );
};

const useForm = (): FormCtxValue => {
  const v = React.useContext(FormCtx);
  if (!v) throw new Error("ChatPanel.Input / Submit must be inside <ChatPanel.Form>");
  return v;
};

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------
export interface ChatPanelInputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "value" | "onChange"> {
  /** Optional controlled override. */
  value?: string;
  onValueChange?: (v: string) => void;
}

const Input: React.FC<ChatPanelInputProps> = ({ value, onValueChange, ...rest }) => {
  const form = useForm();
  return (
    <input
      data-freebird-chat-input=""
      type="text"
      value={value ?? form.value}
      onChange={(e) => {
        onValueChange?.(e.target.value);
        form.setValue(e.target.value);
      }}
      disabled={form.streaming || !form.sessionReady || rest.disabled}
      {...rest}
    />
  );
};

// ---------------------------------------------------------------------------
// Submit
// ---------------------------------------------------------------------------
export interface ChatPanelSubmitProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    SlotProps {}

const Submit: React.FC<ChatPanelSubmitProps> = (props) => {
  const form = useForm();
  const disabled =
    form.streaming || !form.sessionReady || !form.value.trim() || props.disabled;
  return slotWith("button", {
    type: "submit",
    ...props,
    disabled,
    "data-freebird-chat-submit": "",
    "data-streaming": form.streaming ? "" : undefined,
  } as any);
};

// ---------------------------------------------------------------------------
// Citations (chips under an assistant reply; also composable standalone)
// ---------------------------------------------------------------------------
export interface ChatPanelCitationsProps {
  message: ChatMessage;
  /** Client-side routing hook for cross-page citations. */
  onCitationNavigate?: CitationNavigateHandler;
  className?: string;
}

const Citations: React.FC<ChatPanelCitationsProps> = ({
  message,
  onCitationNavigate,
  className,
}) => {
  if (message.role !== "assistant") return null;
  const citations = citationsFromToolPayload(message.toolPayload);
  if (citations.length === 0) return null;
  return (
    <div data-freebird-chat-citations="" className={className}>
      {citations.map((citation, i) => (
        <button
          key={`${citation.componentId}-${i}`}
          type="button"
          data-freebird-chat-citation=""
          data-kind={citation.kind ?? "component"}
          data-component={citation.componentId}
          onClick={() =>
            void activateCitation(citation, {
              ...(onCitationNavigate ? { onNavigate: onCitationNavigate } : {}),
            })
          }
        >
          {citation.title}
        </button>
      ))}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Message (convenience renderer for a single message)
// ---------------------------------------------------------------------------
export interface ChatPanelMessageProps extends React.HTMLAttributes<HTMLDivElement> {
  message: ChatMessage;
  /** Client-side routing hook for cross-page citation chips. */
  onCitationNavigate?: CitationNavigateHandler;
}

const Message: React.FC<ChatPanelMessageProps> = ({
  message,
  onCitationNavigate,
  ...rest
}) => (
  <div
    data-freebird-chat-message=""
    data-role={message.role}
    {...rest}
  >
    {message.content}
    {message.references.length > 0 && (
      <div data-freebird-chat-refs="">
        {message.references.map((r, i) => (
          <span key={i} data-freebird-chat-ref="" data-tag={r.tag} data-component={r.componentId}>
            {r.reason}
          </span>
        ))}
      </div>
    )}
    <Citations
      message={message}
      {...(onCitationNavigate ? { onCitationNavigate } : {})}
    />
  </div>
);

export const ChatPanel = {
  Root,
  Messages,
  Form,
  Input,
  Submit,
  Message,
  Citations,
};
