// packages/react/src/components/ActionPreview.tsx
import React from "react";
import type { PendingAction } from "@freebirdai/core";
import { useActionState } from "../hooks/useActionState.js";

export interface ActionPreviewRenderProps {
  pending: PendingAction;
  /** Phase from the state machine — useful for disabling buttons while executing. */
  phase: "collecting" | "awaiting_confirmation" | "executing" | "error";
  /** Latest validation/handler error. */
  error?: string;
  confirm: () => Promise<void>;
  cancel: (reason?: string) => Promise<void>;
  pause: (label?: string) => void;
}

export interface ActionPreviewProps {
  /**
   * Render-prop API. Use when you want a fully custom preview UI.
   *
   * @example
   * <ActionPreview>
   *   {({ pending, confirm, cancel }) => (
   *     <Card>
   *       <pre>{JSON.stringify(pending.args, null, 2)}</pre>
   *       <button onClick={() => confirm()}>Apply</button>
   *       <button onClick={() => cancel()}>Cancel</button>
   *     </Card>
   *   )}
   * </ActionPreview>
   */
  children?: (props: ActionPreviewRenderProps) => React.ReactNode;
  /**
   * Optional fallback rendered when the children render-prop is omitted.
   * Defaults to a minimal unstyled `<div data-freebird-action-preview>`
   * with raw JSON, two buttons, and ARIA roles. Hosts almost always
   * override this — that's the point of headless.
   */
  fallback?: (props: ActionPreviewRenderProps) => React.ReactNode;
  /** Hide the preview while the action is executing. Default: false. */
  hideWhileExecuting?: boolean;
}

/**
 * Headless action confirmation preview.
 *
 * Renders nothing when there's no pending action (or the action is in
 * `idle`). Otherwise calls the `children` render-prop with the pending
 * action and the three control verbs (confirm/cancel/pause).
 *
 * Pair with the `freebird.action-preview` registered component (see
 * `@freebirdai/react-tailwind`) for a styled default, or roll your own.
 */
export const ActionPreview: React.FC<ActionPreviewProps> = ({
  children,
  fallback,
  hideWhileExecuting = false,
}) => {
  const { phase, pending, lastError, confirm, cancel, pause } = useActionState();
  if (!pending || phase === "idle") return null;
  if (hideWhileExecuting && phase === "executing") return null;
  const renderProps: ActionPreviewRenderProps = {
    pending,
    phase: phase as ActionPreviewRenderProps["phase"],
    error: lastError,
    confirm,
    cancel,
    pause,
  };
  if (children) return <>{children(renderProps)}</>;
  if (fallback) return <>{fallback(renderProps)}</>;
  return <DefaultPreview {...renderProps} />;
};

const DefaultPreview: React.FC<ActionPreviewRenderProps> = (p) => (
  <div
    role="dialog"
    aria-label="Confirm action"
    data-freebird-action-preview=""
    data-phase={p.phase}
  >
    <div data-freebird-action-preview-header="">
      <strong>
        {p.pending.label ??
          `${p.pending.componentId}:${p.pending.actionId}`}
      </strong>
    </div>
    <pre data-freebird-action-preview-body="">
      {JSON.stringify(p.pending.args, null, 2)}
    </pre>
    {p.error ? (
      <div role="alert" data-freebird-action-preview-error="">
        {p.error}
      </div>
    ) : null}
    <div data-freebird-action-preview-actions="">
      <button
        type="button"
        onClick={() => p.confirm()}
        disabled={p.phase === "executing" || p.phase === "collecting"}
        data-freebird-action-confirm=""
      >
        Confirm
      </button>
      <button
        type="button"
        onClick={() => p.cancel()}
        data-freebird-action-cancel=""
      >
        Cancel
      </button>
      <button
        type="button"
        onClick={() => p.pause()}
        data-freebird-action-pause=""
      >
        Pause
      </button>
    </div>
  </div>
);

// guide/packages/angular/src/components/action-preview.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  Input,
  TemplateRef,
  computed,
  inject,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import type { ActionPhase, PendingAction } from "@freebirdai/core";
import { FreeBirdService } from "../services/freebird.service";

/**
 * Headless action confirmation preview.
 *
 * Renders nothing while the action machine is idle. When a pending action
 * exists, projects either:
 *   1. Your `<ng-template>` content (preferred) — receives a render context
 *      `{ pending, phase, error, confirm, cancel, pause }`.
 *   2. A minimal default UI with stable `data-freebird-action-*` hooks.
 *
 * @example
 *   <fb-action-preview>
 *     <ng-template let-pending="pending" let-confirm="confirm" let-cancel="cancel">
 *       <my-card>
 *         <pre>{{ pending.args | json }}</pre>
 *         <button (click)="confirm()">Apply</button>
 *         <button (click)="cancel()">Cancel</button>
 *       </my-card>
 *     </ng-template>
 *   </fb-action-preview>
 */
@Component({
  selector: "fb-action-preview",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-container *ngIf="visible()">
      <ng-container
        *ngIf="tpl; else fallback"
        [ngTemplateOutlet]="tpl"
        [ngTemplateOutletContext]="ctx()"
      />
      <ng-template #fallback>
        <div
          role="dialog"
          aria-label="Confirm action"
          data-freebird-action-preview
          [attr.data-phase]="fb.actionPhase()"
        >
          <div data-freebird-action-preview-header>
            <strong>{{ pending()!.label || pending()!.componentId + ":" + pending()!.actionId }}</strong>
          </div>
          <pre data-freebird-action-preview-body>{{ pending()!.args | json }}</pre>
          <div
            *ngIf="fb.actionState().lastError as err"
            role="alert"
            data-freebird-action-preview-error
          >
            {{ err }}
          </div>
          <div data-freebird-action-preview-actions>
            <button
              type="button"
              data-freebird-action-confirm
              [disabled]="
                fb.actionPhase() === 'executing' || fb.actionPhase() === 'collecting'
              "
              (click)="confirm()"
            >
              Confirm
            </button>
            <button type="button" data-freebird-action-cancel (click)="cancel()">
              Cancel
            </button>
            <button type="button" data-freebird-action-pause (click)="pause()">
              Pause
            </button>
          </div>
        </div>
      </ng-template>
    </ng-container>
  `,
})
export class ActionPreviewComponent {
  readonly fb = inject(FreeBirdService);

  /** When true, suppresses the preview while an action is mid-execution. */
  @Input() hideWhileExecuting = false;

  @ContentChild(TemplateRef) tpl?: TemplateRef<{
    $implicit: PendingAction;
    pending: PendingAction;
    phase: ActionPhase;
    error: string | undefined;
    confirm: () => Promise<void>;
    cancel: (reason?: string) => Promise<void>;
    pause: (label?: string) => void;
  }>;

  readonly pending = computed(() => this.fb.pendingAction());

  readonly visible = computed(() => {
    const p = this.fb.pendingAction();
    if (!p) return false;
    if (this.fb.actionPhase() === "idle") return false;
    if (this.hideWhileExecuting && this.fb.actionPhase() === "executing")
      return false;
    return true;
  });

  readonly ctx = computed(() => {
    const p = this.fb.pendingAction()!;
    return {
      $implicit: p,
      pending: p,
      phase: this.fb.actionPhase(),
      error: this.fb.actionState().lastError,
      confirm: () => this.fb.confirmAction(),
      cancel: (reason?: string) => this.fb.cancelAction(reason),
      pause: (label?: string) => this.fb.pauseAction(label),
    };
  });

  confirm(): Promise<void> {
    return this.fb.confirmAction();
  }
  cancel(): Promise<void> {
    return this.fb.cancelAction();
  }
  pause(): void {
    this.fb.pauseAction();
  }
}
